import {
  Age_group,
  Competition_type,
  CompetitionStatus,
  Dominant_foot,
  MatchResult,
  MatchStatus,
  Player_status,
  Playoffs_round,
} from "./definitions";


export const months = [
  "january",
  "february",
  "march",
  "april",
  "may",
  "june",
  "july",
  "august",
  "september",
  "october",
  "november",
  "december",
];

export const landing_visuals = [
  "/images/home-header-bg.png",
  "/images/contact.jpg",
  "/images/trophy-boy.jpg",
  "/images/results.jpg",
];

export const visuals = [
  "/images/blvsig.png",
  "/images/contact.jpg",
  "/images/trophy-boy.jpg",
  "/images/home-header-bg.png",
  "/images/results.jpg",
  "/images/trials.png",
  "/images/results.jpg",
];

export const teams = [
  {
    id: "f7dccbf7-d187-465d-918f-7760444e839c",
    shortName: "blfa",
    longName: "beyond limits fa",
    logo: "/images/beyondimitslogo.png",
    isBeyondLimits: true,
    stadium: "Remo stars stadium",
  },
  {
    id: "07b1ea51-73a7-41eb-aae1-9dff2500d50a",
    shortName: "imfc",
    longName: "imperial fc",
    logo: "/images/imperial_fc.png",
    isBeyondLimits: false,
    stadium: "surulere stadium",
  },
  {
    id: "8bc32940-d9a7-43c4-8af9-7313a7d8b9c1",
    shortName: "gfc",
    longName: "gbagada fc",
    logo: "/images/gbagada_fc.png",
    isBeyondLimits: false,
    stadium: "gbagada stadium",
  },
  {
    id: "4cd32940-d9a7-43c4-4ac9-7313a7d8b9b2",
    shortName: "cc-u19",
    longName: "carrarese u19",
    logo: "/images/carrarese_u19.png",
    isBeyondLimits: false,
    stadium: "Stadio dei Marmi",
  },
  {
    id: "2cd32920-d9a7-33d4-4ac9-7213b7d8b9b2",
    shortName: "f-u19",
    longName: "fioretina u19",
    logo: "/images/fioretina_u19.png",
    isBeyondLimits: false,
    stadium: "Stadio Curva Fiesole - Viola Park",
  },
  {
    id: "2fd32420-d9b4-22c5-4ac9-7213b7d8b9b3",
    shortName: "cz-u19",
    longName: "crvena-zvezda u19",
    logo: "/images/crvena-zvezda_u19.png",
    isBeyondLimits: false,
    stadium: "Rajko Mitić - Jug veštačka trava 4",
  },
  {
    id: "2cd42420-d9b4-32c5-4ac9-7213b7d8b9b3",
    shortName: "a-u19",
    longName: "avellino u19",
    logo: "/images/avellino_u19.png",
    isBeyondLimits: false,
    stadium: "Stadio Partenio-Adriano Lombardi",
  },
  {
    id: "2cc42120-d9b4-32c5-4ad9-7214b7d8b9b3",
    shortName: "t-u19",
    longName: "torino u19",
    logo: "/images/torino_u19.png",
    isBeyondLimits: false,
    stadium: "Stadio Valentino Mazzola",
  },
  {
    id: "2dc52120-d9b4-32c5-4ad9-3214b4d8b9b3",
    shortName: "oc-u19",
    longName: "ojodu city u19",
    logo: "/images/ojodu-city_u19.png",
    isBeyondLimits: false,
    stadium: "Ojodu stadium",
  },
  {
    id: "2cc32121-d9b4-32c5-4ad9-3214b4d8b9b3",
    shortName: "b-u19",
    longName: "brazzaville u19",
    logo: "/images/brazzaville_u19.png",
    isBeyondLimits: false,
    stadium: "",
  },
];

const similar_attributes = [
  "tackles",
  "interceptions",
  "deuls_won",
  "blocks",
  "clearance",
];

export const player_positions = [
  {
    id: "4ddb4b61-3b45-44b5-b21b-4ab385b8eb94",
    shortName: "gk",
    longName: "goalkeeper",
    players: [],
    attributes: [
      "clean_sheat",
      "saves",
      "goals_conceded",
      "clearance",
      "successful_passes",
    ],
  },
  {
    id: "63650e97-8fcb-43ac-8e5a-3d1ca8904e38",
    shortName: "fb",
    longName: "fullback",
    players: [],
    attributes: [...similar_attributes, "crosses", "dribbles"],
  },
  {
    id: "7622d8ad-708f-4ddb-90b0-e30cec744e7f",
    shortName: "cb",
    longName: "central back",
    players: [],
    attributes: [...similar_attributes],
  },
  {
    id: "737aeebc-23c0-4811-8d65-3c42b6e5f25c",
    shortName: "dm",
    longName: "defensive midfielder",
    players: [],
    attributes: [...similar_attributes, "successful_passes"],
  },
  {
    id: "cc3a4a86-a091-4099-be7a-2e1b061e330a",
    shortName: "cm",
    longName: "central midfielder",
    players: [],
    attributes: [
      ...similar_attributes,
      "successful_passes",
      "shots",
      "dribbles",
      "successful_dribbles",
    ],
  },
  {
    id: "ddbd8b40-892f-4e0a-9a0d-0c34584094c6",
    shortName: "am",
    longName: "attacking midfielder",
    players: [],
    attributes: [
      "passes",
      "successful_passes",
      "shots",
      "dribbles",
      "successful_dribbles",
      "crosses",
      "successful_crosses",
    ],
  },
  {
    id: "ee636c92-087b-457d-9418-dccd90423838",
    shortName: "w",
    longName: "winger",
    players: [],
    attributes: [
      "successful_passes",
      "shots",
      "dribbles",
      "successful_dribbles",
      "crosses",
      "successful_crosses",
    ],
  },
  {
    id: "3bc2934b-f7eb-47b5-af55-ecee0bbbe6a8",
    shortName: "st",
    longName: "striker",
    players: [],
    attributes: ["shots", "shots_on", "dribbles", "attacking_duels_won"],
  },
];

export const dummy_players = [
  {
    id: "055d368e-3f4d-4d12-903b-e4aac2633993",
    firstname: "John",
    lastname: "Doe",
    playerPositionId: "4ddb4b61-3b45-44b5-b21b-4ab385b8eb94",
    squadNo: 1,
    dob: "2007-3-10",
    height: 175,
    weight: 78,
    dominantFoot: Dominant_foot.RIGHT,
    isTwoFooted: true,
    homeKit: "https://res.cloudinary.com/dsb7f77m5/image/upload/v1747007056/beyondlimitsfa/daniel-arierhi-homekit.jpg",
    awayKit: "/images/player-2.png",
    ageGroup: Age_group.UNDER_19,
    status: Player_status.ACTIVE,
  },
  {
    id: "2cc2934b-f7eb-47b5-af55-ecee0bbbe4a4",
    playerPositionId: "737aeebc-23c0-4811-8d65-3c42b6e5f25c",
    squadNo: 4,
    firstname: "Seyi",
    lastname: "Olofin",
    dob: "2012-5-2",
    height: 180,
    weight: 81,
    dominantFoot: Dominant_foot.RIGHT,
    isTwoFooted: true,
    homeKit: "https://res.cloudinary.com/dsb7f77m5/image/upload/v1747006777/beyondlimitsfa/chukwudi-isaac-homekit.jpg",
    awayKit: "/images/player-2.png",
    ageGroup: Age_group.UNDER_19,
    status: Player_status.ACTIVE,
  },
  {
    id: "cc8586e3-b78c-4680-ad20-7fe25f5398fb",
    firstname: "Emeka",
    lastname: "Ojiofor",
    playerPositionId: "cc3a4a86-a091-4099-be7a-2e1b061e330a",
    squadNo: 17,
    dob: "2008-5-10",
    height: 170,
    weight: 75,
    dominantFoot: Dominant_foot.LEFT,
    isTwoFooted: false,
    homeKit: "https://res.cloudinary.com/dsb7f77m5/image/upload/v1747006777/beyondlimitsfa/chukwudi-isaac-homekit.jpg",
    awayKit: "/images/player-2.png",
    ageGroup: Age_group.UNDER_19,
    status: Player_status.ACTIVE,
  },
  {
    id: "cb8586e3-b78c-4680-ad20-7fe25f5398fb",
    firstname: "Okpala",
    lastname: "Uche",
    playerPositionId: "cc3a4a86-a091-4099-be7a-2e1b061e330a",
    squadNo: 18,
    dob: "2008-5-10",
    height: 168,
    weight: 74,
    dominantFoot: Dominant_foot.LEFT,
    isTwoFooted: false,
    homeKit: "https://res.cloudinary.com/dsb7f77m5/image/upload/v1747007056/beyondlimitsfa/daniel-arierhi-homekit.jpg",
    awayKit: "/images/player-2.png",
    ageGroup: Age_group.UNDER_19,
    status: Player_status.ACTIVE,
  },
  {
    id: "2b4586e3-b78c-4680-ad20-7fe25f5398fb",
    firstname: "Olamilekan",
    lastname: "Adegoyega",
    playerPositionId: "cc3a4a86-a091-4099-be7a-2e1b061e330a",
    squadNo: 17,
    dob: "2011-5-10",
    height: 172,
    weight: 80,
    dominantFoot: Dominant_foot.RIGHT,
    isTwoFooted: false,
    homeKit: "https://res.cloudinary.com/dsb7f77m5/image/upload/v1747007056/beyondlimitsfa/daniel-arierhi-homekit.jpg",
    awayKit: "/images/player-2.png",
    ageGroup: Age_group.UNDER_19,
    status: Player_status.ACTIVE,
  },
  {
    id: "2c4584e3-c78c-2680-ad20-7fe25f5398fb",
    firstname: "Taiwo-Cole",
    lastname: "Oyetunde",
    playerPositionId: "cc3a4a86-a091-4099-be7a-2e1b061e330a",
    squadNo: 15,
    dob: "2011-4-21",
    height: 175,
    weight: 75,
    dominantFoot: Dominant_foot.LEFT,
    isTwoFooted: false,
    homeKit: "https://res.cloudinary.com/dsb7f77m5/image/upload/v1747007056/beyondlimitsfa/daniel-arierhi-homekit.jpg",
    awayKit: "/images/player-2.png",
    ageGroup: Age_group.UNDER_17,
    status: Player_status.ACTIVE,
  },
  {
    id: "3bc2934b-f7eb-47b5-af55-ecee0bbbe4a4",
    playerPositionId: "3bc2934b-f7eb-47b5-af55-ecee0bbbe6a8",
    squadNo: 7,
    firstname: "Aiyenugba",
    lastname: "Daniel",
    dob: "2011-5-2",
    height: 170,
    weight: 82,
    dominantFoot: Dominant_foot.LEFT,
    isTwoFooted: true,
    homeKit: "https://res.cloudinary.com/dsb7f77m5/image/upload/v1747007056/beyondlimitsfa/daniel-arierhi-homekit.jpg",
    awayKit: "/images/player-2.png",
    ageGroup: Age_group.UNDER_19,
    status: Player_status.ACTIVE,
  },
  {
    id: "2cc2934b-f7bb-27c5-af35-ecee0bbbe4a4",
    playerPositionId: "3bc2934b-f7eb-47b5-af55-ecee0bbbe6a8",
    squadNo: 9,
    firstname: "Aiyenugba",
    lastname: "Daniel",
    dob: "2011-5-2",
    height: 170,
    weight: 82,
    dominantFoot: Dominant_foot.RIGHT,
    isTwoFooted: true,
    homeKit: "https://res.cloudinary.com/dsb7f77m5/image/upload/v1747007056/beyondlimitsfa/daniel-arierhi-homekit.jpg",
    awayKit: "/images/player-2.png",
    ageGroup: Age_group.UNDER_19,
    status: Player_status.ACTIVE,
  },
  {
    id: "2b4584d3-c78c-2480-ad20-7fe25f5398fb",
    firstname: "Shina",
    lastname: "Ayodele",
    playerPositionId: "3bc2934b-f7eb-47b5-af55-ecee0bbbe6a8",
    squadNo: 8,
    dob: "2006-06-22",
    height: 175,
    weight: 75,
    dominantFoot: Dominant_foot.RIGHT,
    isTwoFooted: false,
    homeKit: "https://res.cloudinary.com/dsb7f77m5/image/upload/v1747007056/beyondlimitsfa/daniel-arierhi-homekit.jpg",
    awayKit: "/images/player-2.png",
    ageGroup: Age_group.UNDER_19,
    status: Player_status.ACTIVE,
  },
];

export const socials = [
  {
    id: 21,
    link: "https://x.com/beyond_limitsfa?s=11&t=a_AA_bkBcHWDpD2WBldopQ",
    icon: "/images/pajamas_twitter.svg",
    name: "Twitter",
  },
  {
    id: 22,
    link: "https://www.instagram.com/beyondlimits_fa?igsh=MXdiM3gwaTBkNGd5Yg==",
    icon: "/images/bi_instagram.svg",
    name: "Twitter",
  },
  {
    id: 23,
    link: "https://x.com/beyond_limitsfa?s=11&t=a_AA_bkBcHWDpD2WBldopQ",
    icon: "/images/ph_tiktok-logo.svg",
    name: "Tiktok",
  },
  {
    id: 24,
    link: "https://youtube.com/@beyondlimitsfootballacadem7276?si=UrDiLOAy9c6j8jDM",
    icon: "/images/ant-design_youtube-outlined.svg",
    name: "Youtube",
  },
];
